services:
#  mongodb:
#    image: 'mongo:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#    ports:
#      - '27017'

  redis-master:
    container_name: "redis-master"
    image: 'redis:latest'
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
  redis-slave1:
    container_name: "redis-slave1"
    image: 'redis:latest'
    ports:
      - "6380:6379"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server --slaveof redis-master 6379
  redis-slave2:
    container_name: "redis-slave2"
    image: 'redis:latest'
    ports:
      - "6381:6379"
    volumes:
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server --slaveof redis-master 6379
  redis-sentinel:
    container_name: 'redis-sentinel'
    image: 'redis:latest'
    ports:
      - "5000:5000"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./sentinel/sentinel.conf:/etc/sentinel.conf"
